version: "3.7"

volumes:
  odoo-data:
  odoo-testlogs:
  psql:

services:
  odoo:
    image: iterativodo/dockerdoo:${ODOO_VERSION}
    env_file: .env
    
    restart: unless-stopped

    ports: ["8069:8069", "8072:8072"]

    volumes:
      # Host paths (addons & conf)
      - ./custom:${ODOO_EXTRA_ADDONS}:delegated
      # Named volumes
      - odoo-data:${ODOO_DATA_DIR}
      - odoo-testlogs:${ODOO_LOGS_DIR}
    labels:
      - 'traefik.http.routers.${RESOLVER_NAME}.rule=Host(`${ODOO_TRAEFIK_URL_COMPANY}`)'
      - 'traefik.http.routers.${RESOLVER_NAME}.entrypoints=websecure'
      - 'traefik.http.routers.${RESOLVER_NAME}.tls.certresolver=${RESOLVER_NAME}'
      - 'traefik.port=8069'
      - "traefik.docker.network=odoonet"

    depends_on:
      - db
  # ------------------------
  db:
    image: postgres:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata

networks:
  web:
    external:
      name: odoonet
